version: "3.9"

services: 
  postgres:
    image: postgres:15 
    environment: 
      POSTGRES_USER: ops
      POSTGRES_PASSWORD: ops
      POSTGRES_DB: opscentral
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ops:ops@postgres:5432/opscentral
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
  
volumes:
  pgdata: